UploadBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: UploadBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: string
            length: 255


    oneToOne:
        picture:
            targetEntity: UploadBundle\Entity\Picture
            cascade: ['all']

    lifecycleCallbacks: {  }
