UploadBundle\Entity\Picture:
    type: entity
    table: null
    repositoryClass: UploadBundle\Repository\PictureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        src:
            type: string
            length: 255
        alt:
            type: string
            length: 255

    lifecycleCallbacks:
        # For create
        prePersist: [ preUpload ]
        postPersist: [ upload ]

        # For edit
        preUpdate: [ preUpload ]
        postUpdate: [ upload ]

        # For remove
        postRemove: [ remove ]

