services:
#    upload.example:
#        class: UploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    blog.uploader:
        class: UploadBundle\Services\FileUploader
        arguments: ['%upload_directory%']